{
 "title": "External Node",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stage) (rate(server_processed_txs{stage=~\"mempool_added\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Last processed batch by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (stage) (external_node_fetcher_l1_batch)"
    }
   ]
  },
  {
   "title": "Sync lag (blocks)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (stage) (external_node_sync_lag)"
    }
   ]
  },
  {
   "title": "Total disk space usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (rocksdb_total_sst_size)",
     "legendFormat": "RocksDB"
    },
    {
     "expr": "sum by (job) (postgres_table_total_size_bytes)",
     "legendFormat": "PostgresSQL"
    }
   ]
  }
 ]
}