apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer-app
  template:
    metadata:
      labels:
        app: explorer-app
    spec:
      containers:
      - name: explorer-app
        imagePullPolicy: "Always"
        image: us-central1-docker.pkg.dev/zksync-413615/zksync/block-explorer-app:ihc-testnet-v0.0.2
        ports:
        - containerPort: 3010
        env:
          - name: PORT
            value: '3010'
