apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaf-witness-generator-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaf-witness-generator
  template:
    metadata:
      labels:
        app: leaf-witness-generator
    spec:
      serviceAccountName: buckets-rw
      containers:
      - name: leaf-witness-generator
        args: ["--round=leaf_aggregation"]
        image: us-central1-docker.pkg.dev/zksync-413615/zksync/witness-generator:0.24.2-v16.1.0
        ports:
        - containerPort: 3116
        env:
        - name: API_PROMETHEUS_LISTENER_PORT
          value: '3116'
        envFrom:
          - configMapRef:
              name: env-configmap
