apiVersion: v1
kind: ConfigMap
metadata:
  name: html
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>Error Grafana</title>
    </head>
    <body>
      <h2>Error</h2>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend-ingress-grafana
spec:
  selector:
    matchLabels:
      app: default-backend-ingress-grafana
  template:
    metadata:
      labels:
        app: default-backend-ingress-grafana

    spec:
      containers:
      - name: default-backend-ingress-grafana
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        ports:
        - containerPort: 80
      volumes:
      - name: html-volume
        configMap:
          name: html
---
apiVersion: v1
kind: Service
metadata:
  name: default-backend-ingress-grafana-service
spec:
  type: NodePort
  selector:
    app: default-backend-ingress-grafana
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
