apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-node-grafana
  namespace: {{.Values.namespace}}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{.Values.terraform.grafana.ip}}
    cert-manager.io/issuer: http01-issuer
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: external-node-grafana
spec:
  defaultBackend:
    service:
      name: default-backend-ingress-grafana-service
      port:
        number: 80
  rules:
    - host: {{.Values.terraform.grafana.dns}}
      http:
        paths:
        {{- range .Values.nodename }}
          - pathType: Prefix
            path: "/{{.}}"
            backend:
              service:
                name: {{.}}-grafana
                port:
                  number: 3000
        {{- end }}
  tls:
    - hosts:
      - {{.Values.terraform.grafana.dns}}
      secretName: external-node-grafana-ingress-cert
