apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-node
  namespace: {{.Values.namespace}}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{.Values.terraform.rpc.ip}}
    cert-manager.io/issuer: http01-issuer
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: external-node
spec:
  rules:
    - host: {{.Values.terraform.rpc.dns}}
      http:
        paths:
          {{- range .Values.nodename }}
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{.}}-service
                port:
                  number: 3050
          {{- end }}
  tls: 
    - hosts:
        - {{.Values.terraform.rpc.dns}}
      secretName: external-node-ingress-cert
