apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-node
  namespace: default
  annotations:
    kubernetes.io/ingress.global-static-ip-name: external-node-ip
    cert-manager.io/issuer: http01-issuer
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: external-node
spec:
  rules:
    - host: k8s.en01.rpc.sepolia.zk-stack.lambdaclass.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: external-node-service
                port:
                  number: 3050
  tls:
    - hosts:
        - k8s.en01.rpc.sepolia.zk-stack.lambdaclass.com
      secretName: external-node-ingress-cert
