apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal
  namespace: default
  annotations:
    kubernetes.io/ingress.global-static-ip-name: portal-ip
    cert-manager.io/issuer: http01-issuer
    acme.cert-manager.io/http01-edit-in-place: "true"
    networking.gke.io/v1beta1.FrontendConfig: "http-https-redirect"
  labels:
    app: portal
spec:
  rules:
    - host: k8s.portal.sepolia.zk-stack.lambdaclass.com
      http:
        paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: portal-service
              port:
                number: 3000
  tls:
    - hosts:
      - k8s.portal.sepolia.zk-stack.lambdaclass.com
      secretName: portal-ssl-cert
