apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server
  namespace: default
  annotations:
    kubernetes.io/ingress.global-static-ip-name: server-ip
    cert-manager.io/issuer: dns01-cloudflare-issuer
    acme.cert-manager.io/http01-edit-in-place: "true"
    networking.gke.io/v1beta1.FrontendConfig: "http-https-redirect"
  labels:
    app: server
spec:
  rules:
    - host: k8s.rpc.sepolia.zk-stack.lambdaclass.com
      http:
        paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: server
              port:
                number: 3050
  tls:
    - hosts:
      - k8s.rpc.sepolia.zk-stack.lambdaclass.com
      secretName: server-ingress-cert
