apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store-gcp
spec:
  provider:
    gcpsm:
      projectID: zksync-413615
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: zksync-dev-01
          clusterProjectID: zksync-413615
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
