apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: health-check-config
  namespace: default
spec:
  healthCheck:
    checkIntervalSec: {{ .Values.healthCheck.checkIntervalSec }}
    port: {{ .Values.healthCheck.port }}
    type: HTTP
    requestPath: /health
