__imports__ = [ "base", "l1-inits/.init.env", "l2-inits/custom.init.env" ]

ETH_SENDER_SENDER_PUBDATA_SENDING_MODE = "Blobs"

[chain.eth]
network = "sepolia"

[chain.state_keeper]
fee_account_addr = ""

[eth_client]
web3_url = "https://sepolia.internal.lambdaclass.com/"

[eth_sender.sender]
operator_private_key = ""
operator_commit_eth_addr = ""

operator_blobs_private_key = ""
operator_blobs_eth_addr = ""

proof_sending_mode = "SkipEveryProof"

[misc]
fee_account_private_key = ""

[contracts]
BASE_TOKEN_ADDR = "0x0000000000000000000000000000000000000001"

[contract_verifier]
url = "http://server:3070"

[api.web3_json_rpc]
http_url = "http://server:3050"
ws_url = "ws://server:3051"

[api.prometheus]
pushgateway_url = "http://pushgateway:9091"

[fri_prover_gateway]
api_url="http://server:3320"
prometheus_pushgateway_url = "http://pushgateway:9091"

[fri_prover]
setup_data_path = "prover/vk_setup_data_generator_server_fri/data"

[fri_proof_compressor]
universal_setup_path = "../keys/setup/setup_2^26.key"
prometheus_pushgateway_url = "http://pushgateway:9091"

[fri_witness_vector_generator]
prometheus_pushgateway_url = "http://pushgateway:9091"

[object_store]
mode="GCS"
bucket_base_url="object-store-dev"

[public_object_store]
mode="GCS"
bucket_base_url="public-object-store-dev"

[prover_object_store]
mode="GCS"
bucket_base_url="prover-object-store-dev"

[snapshots_object_store]
mode="GCS"
bucket_base_url="snapshots-object-store-dev"
