apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trusted-setup-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 32Gi
