apiVersion: v1
kind: ServiceList
items:
  - metadata:
      name: en01-grafana
      namespace: default
      labels:
        app: en01-grafana
    spec:
      type: NodePort
      ports:
        - name: en01-grafana
          port: 3000
          targetPort: 3000
          protocol: TCP
      selector:
        app: en01-grafana
  - metadata:
      name: en01-prometheus
      namespace: default
      labels:
        app: en01-prometheus
    spec:
      type: NodePort
      ports:
        - name: en01-prometheus
          port: 9090
          targetPort: 9090
          protocol: TCP
      selector:
        app: en01-grafana
  - metadata:
      name: en01-pushgateway
      namespace: default
      labels:
        app: en01-prometheus
    spec:
      type: NodePort
      ports:
        - name: pushgateway
          port: 9091
          targetPort: 9091
          protocol: TCP
      selector:
        app: en01-grafana
  - metadata:
      name: en01-nodeexporter
      namespace: default
      labels:
        app: en01-prometheus
    spec:
      type: NodePort
      ports:
        - name: nodeexporter
          port: 9100
          targetPort: 9100
          protocol: TCP
      selector:
        app: en01-grafana
