apiVersion: v1
kind: Service
metadata:
  name: explorer-api-service
  namespace: default
  labels:
    app: explorer-api
spec:
  type: NodePort
  ports:
  - port: 3020
    targetPort: 3020
    protocol: TCP
  selector:
    app: explorer-api
