apiVersion: v1
kind: Service
metadata:
  name: explorer-app
  namespace: default
  labels:
    app: explorer-app
spec:
  type: NodePort
  ports:
  - port: 3010
    targetPort: 3010
    protocol: TCP
  selector:
    app: explorer-app
