apiVersion: v1
kind: Service
metadata:
  name: external-node-service
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "external-node-hc-config"}'
  labels:
    app: external-node
spec:
  type: NodePort
  ports:
    - port: 3050
      name: en-http
      targetPort: 3050
      protocol: TCP
    - port: 3071
      name: en-healthcheck
      targetPort: 3071
      protocol: TCP
    - port: 3312
      name: en-prometheus
      targetPort: 3312
      protocol: TCP
  selector:
    app: external-node
