apiVersion: v1
kind: ServiceList
items:
- metadata:
    name: grafana
    namespace: default
    labels:
      app: grafana
  spec:
    type: NodePort
    ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      protocol: TCP
    selector:
      app: grafana
- metadata:
    name: prometheus
    namespace: default
    labels:
      app: prometheus
  spec:
    type: NodePort
    ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      protocol: TCP
    selector:
      app: grafana
- metadata:
    name: pushgateway
    namespace: default
    labels:
      app: prometheus
  spec:
    type: NodePort
    ports:
    - name: pushgateway
      port: 9091
      targetPort: 9091
      protocol: TCP
    selector:
      app: grafana
- metadata:
    name: nodeexporter
    namespace: default
    labels:
      app: prometheus
  spec:
    type: NodePort
    ports:
    - name: nodeexporter
      port: 9100
      targetPort: 9100
      protocol: TCP
    selector:
      app: grafana
- metadata:
    name: alertmanager
    namespace: default
    labels:
      app: prometheus
  spec:
    type: NodePort
    ports:
    - name: alertmanager
      port: 9093
      targetPort: 9093
      protocol: TCP
    selector:
      app: grafana
