apiVersion: v1
kind: Service
metadata:
  name: portal-service
  namespace: default
  labels:
    app: portal
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: portal
