apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "server-hc-config"}'
  labels:
    app: server
spec:
  type: NodePort
  ports:
  - name: server-rpc
    port: 3050
    targetPort: 3050
    protocol: TCP
  - name: server-proof-generation
    port: 3320
    targetPort: 3320
    protocol: TCP
  - name: server-readiness
    port: 3071
    targetPort: 3071
    protocol: TCP
  - name: server-prometheus-listener
    port: 3312
    targetPort: 3312
    protocol: TCP
  selector:
    app: server
