apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: dns01-cloudflare-issuer
spec:
  acme:
    email: infra@lambdaclass.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
