apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: http01-issuer
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http01-issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: ingress-gce
